// Purpose: Join compiler-owned Tea facts with human-written reference metadata and emit the reviewable per-entry reference site.

import {mkdir, readFile, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {format} from 'prettier';

import {
  CATALOG,
  FirstArgumentResult,
  TypeRef,
  type GenericTypeRef,
  type NativeFunc,
  type NativeResult,
  type NativeTypeRef,
} from '../../src/checker/catalog';
import {formatType} from '../../src/ir/type';
import {
  PILOT_REFERENCE_ENTRIES,
  REFERENCE_CATEGORIES,
  REFERENCE_CATEGORY_SUMMARIES,
  type AnnotationEntry,
  type ConstantEntry,
  type FunctionEntry,
  type KeywordEntry,
  type OperatorEntry,
  type ReferenceCategory,
  type ReferenceEntry,
  type ReferenceExample,
  type ReferenceLink,
  type TypeEntry,
  type VariableEntry,
} from './reference-pilot';

const GENERATED_WARNING =
  '{/* Generated by scripts/docs/generate-reference.ts. Do not edit by hand. */}';
const SCRIPT_FILE = fileURLToPath(import.meta.url);
const SCRIPT_DIR = path.dirname(SCRIPT_FILE);

function code(value: string): string {
  return `\`${value.replaceAll('`', '\\`')}\``;
}

function fencedTea(source: string): string {
  return `\`\`\`tea\n${source}\n\`\`\``;
}

function title(category: ReferenceCategory): string {
  return category[0]!.toUpperCase() + category.slice(1);
}

function isGeneric(ref: NativeTypeRef): ref is GenericTypeRef {
  return (
    typeof ref === 'object' &&
    (ref.kind === 'type-param' ||
      ref.kind === 'array' ||
      ref.kind === 'matrix' ||
      ref.kind === 'map')
  );
}

export function formatNativeTypeRef(ref: NativeTypeRef): string {
  if (isGeneric(ref)) {
    if (ref.kind === 'type-param') return ref.name;
    if (ref.kind === 'array' || ref.kind === 'matrix') {
      return `${ref.kind}<${formatNativeTypeRef(ref.element)}>`;
    }
    return `map<${formatNativeTypeRef(ref.key)}, ${formatNativeTypeRef(ref.value)}>`;
  }
  if (ref === TypeRef.Num) return 'int | float';
  if (ref === TypeRef.Any) return 'any value';
  if (ref === TypeRef.Enum) return 'enum';
  if (ref === TypeRef.Nullable) return 'nullable value';
  if (ref === TypeRef.StringConvertible) return 'scalar | enum | resource';
  return formatType(ref);
}

function formatResult(result: NativeResult): string {
  return result === FirstArgumentResult
    ? 'type of first argument'
    : formatNativeTypeRef(result);
}

function typeParams(func: NativeFunc): string {
  if (func.typeParams.length === 0) return '';
  return `<${func.typeParams
    .map(parameter => `${parameter.name}: ${parameter.constraint}`)
    .join(', ')}>`;
}

function signature(func: NativeFunc): string {
  const supported = func.params.filter(
    parameter => parameter.availability === 'supported',
  );
  const params = supported
    .map(parameter => {
      const variadic = parameter.variadic ? '...' : '';
      const optional = parameter.required ? '' : '?';
      return `${variadic}${parameter.name}${optional}: ${formatNativeTypeRef(parameter.type)}`;
    })
    .join(', ');
  return `${func.name}${typeParams(func)}(${params}) → ${formatResult(func.result)}`;
}

function frontmatter(pageTitle: string, description: string): string {
  return `---\ntitle: ${JSON.stringify(pageTitle)}\ndescription: ${JSON.stringify(description)}\n---`;
}

function renderExamples(values: readonly ReferenceExample[]): string {
  return values
    .map(
      example =>
        `### ${example.title}\n\n${example.explanation}\n\n${fencedTea(example.source)}`,
    )
    .join('\n\n');
}

function renderRemarks(values: readonly string[]): string {
  return values.map(value => `- ${value}`).join('\n');
}

function renderLinks(values: readonly ReferenceLink[]): string {
  return values.map(value => `[${value.label}](${value.href})`).join(', ');
}

function renderDescription(entry: ReferenceEntry): string {
  return entry.description.join('\n\n');
}

function commonTail(entry: ReferenceEntry): string {
  return `## Examples\n\n${renderExamples(entry.examples)}\n\n## Remarks\n\n${renderRemarks(entry.remarks)}\n\n## See also\n\n${renderLinks(entry.seeAlso)}`;
}

function typePage(entry: TypeEntry): string {
  const parameters = entry.typeParameters
    .map(parameter => `**${code(parameter.name)}** — ${parameter.description}`)
    .join('\n\n');
  return `${frontmatter(entry.title, entry.summary)}\n\n${GENERATED_WARNING}\n\n## Syntax\n\n${fencedTea(entry.syntax.join('\n'))}\n\n## Type parameters\n\n${parameters}\n\n## Description\n\n${renderDescription(entry)}\n\n## Construction\n\n${renderLinks(entry.construction)}\n\n## Operations\n\n${renderLinks(entry.operations)}\n\n${commonTail(entry)}\n`;
}

function variablePage(entry: VariableEntry): string {
  return `${frontmatter(entry.title, entry.summary)}\n\n${GENERATED_WARNING}\n\n## Type\n\n${code(entry.qualifiedType)}\n\n## Description\n\n${renderDescription(entry)}\n\n${commonTail(entry)}\n`;
}

function constantPage(entry: ConstantEntry): string {
  return `${frontmatter(entry.title, entry.summary)}\n\n${GENERATED_WARNING}\n\n## Type\n\n${code(entry.type)}\n\n## Value\n\n${code(entry.value)}\n\n## Description\n\n${renderDescription(entry)}\n\n${commonTail(entry)}\n`;
}

function functionArguments(
  entry: FunctionEntry,
  overloads: readonly NativeFunc[],
): string {
  const parameters = new Map<string, NativeTypeRef>();
  for (const overload of overloads) {
    for (const parameter of overload.params) {
      if (parameter.availability === 'supported') {
        parameters.set(parameter.name, parameter.type);
      }
    }
  }
  return [...parameters.entries()]
    .map(([name, type]) => {
      const prose = entry.arguments[name];
      if (prose === undefined) {
        throw new Error(
          `reference metadata for ${entry.compilerName} lacks argument '${name}'`,
        );
      }
      return `**${code(name)}** (${code(formatNativeTypeRef(type))}) — ${prose}`;
    })
    .join('\n\n');
}

function functionPage(entry: FunctionEntry): string {
  const overloads = CATALOG.funcs.get(entry.compilerName);
  if (overloads === undefined || overloads.length === 0) {
    throw new Error(`unknown native function '${entry.compilerName}'`);
  }
  const signatures = overloads.map(value => signature(value)).join('\n');
  const errorSection =
    entry.runtimeErrors.length === 0
      ? ''
      : `\n\n## Runtime errors\n\n${renderRemarks(entry.runtimeErrors)}`;
  return `${frontmatter(entry.title, entry.summary)}\n\n${GENERATED_WARNING}\n\n## Syntax\n\n${fencedTea(signatures)}\n\n## Arguments\n\n${functionArguments(entry, overloads)}\n\n## Returns\n\n${entry.returns}\n\n## Description\n\n${renderDescription(entry)}\n\n## Examples\n\n${renderExamples(entry.examples)}\n\n## Remarks\n\n${renderRemarks(entry.remarks)}${errorSection}\n\n## See also\n\n${renderLinks(entry.seeAlso)}\n`;
}

function syntaxParts(
  values: readonly {
    readonly name: string;
    readonly type: string;
    readonly description: string;
  }[],
): string {
  return values
    .map(
      value =>
        `**${code(value.name)}** (${code(value.type)}) — ${value.description}`,
    )
    .join('\n\n');
}

function keywordTypeRelationships(entry: KeywordEntry): string {
  const rows = entry.typeRelationships
    .map(
      relationship =>
        `| ${code(relationship.collection)} | ${code(relationship.form)} | ${code(relationship.bindings)} | ${code(relationship.bindingTypes)} |`,
    )
    .join('\n');
  return `| Collection type | Header form | Local bindings | Binding types |\n| --- | --- | --- | --- |\n${rows}`;
}

function keywordBehavior(entry: KeywordEntry): string {
  return entry.behaviorSections
    .map(section => `## ${section.title}\n\n${section.paragraphs.join('\n\n')}`)
    .join('\n\n');
}

function keywordPage(entry: KeywordEntry): string {
  const relationships =
    entry.typeRelationships.length === 0
      ? ''
      : `\n\n## Type relationships\n\n${keywordTypeRelationships(entry)}`;
  return `${frontmatter(entry.title, entry.summary)}\n\n${GENERATED_WARNING}\n\n## Syntax\n\n${fencedTea(entry.syntax.join('\n\n'))}\n\n## Syntax components\n\n${syntaxParts(entry.parts)}${relationships}\n\n${renderDescription(entry)}\n\n${keywordBehavior(entry)}\n\n${commonTail(entry)}\n`;
}

function operatorPage(entry: OperatorEntry): string {
  return `${frontmatter(entry.title, entry.summary)}\n\n${GENERATED_WARNING}\n\n## Syntax\n\n${fencedTea(entry.syntax.join('\n'))}\n\n## Operands\n\n${syntaxParts(entry.operands)}\n\n## Returns\n\n${entry.returns}\n\n## Description\n\n${renderDescription(entry)}\n\n${commonTail(entry)}\n`;
}

function annotationPage(entry: AnnotationEntry): string {
  return `${frontmatter(entry.title, entry.summary)}\n\n${GENERATED_WARNING}\n\n## Syntax\n\n${fencedTea(entry.syntax.join('\n'))}\n\n## Placement\n\n${entry.placement}\n\n## Effect\n\n${entry.effect}\n\n## Description\n\n${renderDescription(entry)}\n\n${commonTail(entry)}\n`;
}

export function entryPage(entry: ReferenceEntry): string {
  switch (entry.kind) {
    case 'type':
      return typePage(entry);
    case 'variable':
      return variablePage(entry);
    case 'constant':
      return constantPage(entry);
    case 'function':
      return functionPage(entry);
    case 'keyword':
      return keywordPage(entry);
    case 'operator':
      return operatorPage(entry);
    case 'annotation':
      return annotationPage(entry);
  }
}

export function categoryPage(category: ReferenceCategory): string {
  const entries = PILOT_REFERENCE_ENTRIES.filter(
    entry => entry.category === category,
  );
  const list = entries
    .map(entry => `- [${code(entry.title)}](${entry.route}) — ${entry.summary}`)
    .join('\n');
  return `${frontmatter(title(category), REFERENCE_CATEGORY_SUMMARIES[category])}\n\n${GENERATED_WARNING}\n\n${list}\n`;
}

export function overviewPage(): string {
  const categories = REFERENCE_CATEGORIES.map(
    category =>
      `- [${title(category)}](/reference/${category}/) — ${REFERENCE_CATEGORY_SUMMARIES[category]}`,
  ).join('\n');
  return `${frontmatter('Reference', 'Exact lookup documentation for the Tea language and its supported built-ins.')}\n\n${GENERATED_WARNING}\n\nUse the Reference when you need the exact syntax or behavior of a Tea type, value, function, construct, operator, or source annotation. If you are learning Tea, begin with the Documentation section instead.\n\n${categories}\n`;
}

function outputPath(root: string, entry: ReferenceEntry): string {
  const route = entry.route.replace(/^\/reference\//, '').replace(/\/$/, '');
  return path.join(root, 'docs/reference', `${route}.md`);
}

export function referenceOutputs(root: string): ReadonlyMap<string, string> {
  return new Map([
    [path.join(root, 'docs/reference/overview.md'), overviewPage()],
    ...REFERENCE_CATEGORIES.map(
      category =>
        [
          path.join(root, 'docs/reference', `${category}.md`),
          categoryPage(category),
        ] as const,
    ),
    ...PILOT_REFERENCE_ENTRIES.map(
      entry => [outputPath(root, entry), entryPage(entry)] as const,
    ),
  ]);
}

interface GenerateOptions {
  readonly root?: string;
  readonly check?: boolean;
  readonly report?: (message: string) => void;
}

export async function generateReference(
  options: GenerateOptions = {},
): Promise<boolean> {
  const root = options.root ?? path.resolve(SCRIPT_DIR, '../..');
  const check = options.check ?? false;
  const report = options.report ?? (message => console.error(message));
  let stale = false;
  for (const [file, content] of referenceOutputs(root)) {
    const formatted = await format(content, {parser: 'mdx'});
    let current: string | undefined;
    try {
      current = await readFile(file, 'utf8');
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
    if (current === formatted) continue;
    if (check) {
      stale = true;
      report(`Generated reference is stale: ${path.relative(root, file)}`);
      continue;
    }
    await mkdir(path.dirname(file), {recursive: true});
    await writeFile(file, formatted, 'utf8');
  }
  if (!stale && check) console.log('Generated Tea reference is current.');
  return !stale;
}

if (
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === SCRIPT_FILE
) {
  const current = await generateReference({
    check: process.argv.includes('--check'),
  });
  if (!current) process.exitCode = 1;
}
