// Purpose: Project current compiler declarations into complete searchable Markdown inventories.
import {readFileSync, readdirSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {newFileBase, type Pos} from '../../src/base/pos';
import {CATALOG, formatNativeSignature} from '../../src/checker/catalog';
import {PUBLIC_TYPE_CATALOG} from '../../src/checker/type-catalog';
import {formatType, Qualifier} from '../../src/ir/type';
import {NodeKind} from '../../src/syntax/nodes';
import {endPos} from '../../src/syntax/positions';
import {parse} from '../../src/syntax/syntax';

const libraryRoot = fileURLToPath(
  new URL('../../src/tea-lib/', import.meta.url),
);
const warning =
  '{/* Generated by scripts/docs/generate-reference.ts. Do not edit by hand. */}';
const fence = (text: string) => `\`\`\`text\n${text}\n\`\`\``;
const heading = (title: string) =>
  `---\ntitle: ${JSON.stringify(title)}\n---\n\n${warning}\n\n`;

/** Complete native signatures and the call restrictions enforced by the checker. */
export function nativeReference(): string {
  return (
    heading('Native functions') +
    'These declarations come from the compiler used by this version. Optional parameters have a `?`; `...` means variadic. Qualifiers describe the latest-changing value accepted: const, input, simple, series. See [values and control flow](../language-guide/values-and-control-flow.md).\n\n' +
    [...CATALOG.funcs]
      .map(
        ([name, overloads]) =>
          `## ${name}\n\n` +
          overloads
            .map(overload => {
              const captures = overload.params.some(p => p.capture);
              const signature = formatNativeSignature(overload);
              const rules = overload.params
                .filter(p => p.availability === 'supported')
                .map(
                  p =>
                    `- \`${p.name}\`: ${p.qualifierCap}${p.constLiteral ? '; compile-time literal value required' : ''}${p.acceptsNa ? '' : '; cannot be na'}${p.mode === 'inout' ? '; writable binding required' : ''}${p.capture ? '; expression evaluated in the requested stream' : ''}.`,
                )
                .join('\n');
              return `${fence(signature)}\n\n${rules}${captures ? '\n\nThe captured expression determines the result type; see [Requests](../requests.md) for scalar and collected results, supported declaration shapes and synchronization.' : ''}`;
            })
            .join('\n\n'),
      )
      .join('\n\n') +
    '\n'
  );
}

/** Complete public type forms, including which forms cannot annotate bindings. */
export function typesReference(): string {
  return PUBLIC_TYPE_CATALOG.map(
    type =>
      `### ${type.name}\n\n${fence(type.forms.join('\n'))}\n\n${type.summary}`,
  ).join('\n\n');
}

/** All native variables or constants directly from the compiler's sole catalog. */
export function valuesReference(constants: boolean): string {
  return [...CATALOG.vars.values()]
    .filter(value => (value.qualifier === Qualifier.Const) === constants)
    .map(
      value =>
        `### ${value.name}\n\n${fence(`${value.qualifier} ${formatType(value.type)} ${value.name}`)}${value.qualifier === Qualifier.Const ? `\n\nValue: \`${String(value.value)}\`` : ''}`,
    )
    .join('\n\n');
}

function offset(source: string, pos: Pos): number {
  return (
    source
      .split('\n')
      .slice(0, pos.line - 1)
      .reduce((n, line) => n + line.length + 1, 0) +
    pos.col -
    1
  );
}

/** Public library declarations retain their actual parameter names, defaults and qualifiers. */
export function libraryReferences(): ReadonlyMap<string, string> {
  return new Map(
    readdirSync(libraryRoot)
      .filter(file => file.endsWith('.tea'))
      .sort()
      .map(file => {
        const source = readFileSync(path.join(libraryRoot, file), 'utf8');
        const ast = parse(newFileBase(file), source, (pos, message) => {
          throw new Error(`${file}:${pos.line}: ${message}`);
        });
        const name = path.basename(file, '.tea');
        const introduction =
          name === 'ta'
            ? 'Automatically available as `ta.name(...)`. Each written stateful call has its own history and persistent locals. Compute time-series helpers on every step before using their result in a conditional. Parameters without annotations are inferred at call sites; the compiler checks the called body.\n\nFor moving averages and signals, see [time-series calculations](../../language-guide/time-series.md).'
            : name === 'visual'
              ? 'Automatically available without a namespace: call `plot(...)`, `alertcondition(...)` and `alert(...)`. The first argument is always the stable output ID. Plot and alert titles are separate arguments. See [outputs and events](../../language-guide/outputs-and-events.md).'
              : name === 'pine'
                ? 'Automatically available without a namespace: `open`, `high`, `low`, `close`, `volume`, and the derived price aliases read named series columns supplied by the host. These are ordinary `input.series(...)` declarations.'
                : `Use \`import ${name}\` before calling \`${name}.name(...)\`. This is an ordinary Tea library; its presence does not configure a host or connect external services.`;
        const declarations = ast.stmtList.flatMap(stmt => {
          if (!('exported' in stmt) || !stmt.exported) return [];
          const start = offset(source, stmt.pos);
          let declaration: string;
          if (stmt.kind === NodeKind.FuncDecl) {
            declaration = source
              .slice(start, offset(source, stmt.body.pos))
              .trim()
              .replace(/=>\s*$/, '');
          } else if (stmt.kind === NodeKind.StructDecl) {
            declaration =
              source.split('\n')[stmt.pos.line - 1]!.trim() +
              '\n' +
              stmt.members
                .map(member => {
                  const finish =
                    member.kind === NodeKind.MethodDecl
                      ? member.body.pos
                      : endPos(member);
                  return (
                    '    ' +
                    source
                      .slice(offset(source, member.pos), offset(source, finish))
                      .trim()
                      .replace(/=>\s*$/, '')
                  );
                })
                .join('\n');
          } else {
            declaration = source
              .slice(start, offset(source, endPos(stmt)))
              .trim();
          }
          const names =
            stmt.kind === NodeKind.DeclStmt
              ? stmt.target.kind === NodeKind.Name
                ? [stmt.target]
                : stmt.target.elems
              : [stmt.name];
          return names.map(
            exported =>
              `## ${name}.${exported.value}\n\n${fence(declaration)}\n`,
          );
        });
        return [
          name,
          heading(`${name} library`) +
            introduction +
            '\n\n' +
            declarations.join('\n'),
        ];
      }),
  );
}
