// Purpose: Deterministically project compiler-owned native functions and public type forms into the two generated Tea reference pages.

import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {format} from 'prettier';
import {
  CATALOG,
  FirstArgumentResult,
  JoinResult,
  TypeRef,
  type GenericTypeRef,
  type NativeFunc,
  type NativeParam,
  type NativeResult,
  type NativeTypeRef,
} from '../../src/checker/catalog';
import {
  PUBLIC_TYPE_CATALOG,
  type PublicTypeDescriptor,
} from '../../src/checker/type-catalog';
import {formatType, type Qualifier} from '../../src/ir/type';

const GENERATED_WARNING =
  '<!-- Generated by website/scripts/generate-reference.ts. Do not edit by hand. -->';

function compare(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function anchor(prefix: string, name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  return `${prefix}-${slug}`;
}

function code(value: string): string {
  return `\`${value.replaceAll('`', '\\`')}\``;
}

function cell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function isGeneric(ref: NativeTypeRef): ref is GenericTypeRef {
  return (
    typeof ref === 'object' &&
    (ref.kind === 'type-param' ||
      ref.kind === 'array' ||
      ref.kind === 'matrix' ||
      ref.kind === 'map')
  );
}

export function formatNativeTypeRef(ref: NativeTypeRef): string {
  if (isGeneric(ref)) {
    if (ref.kind === 'type-param') {
      return ref.name;
    }
    if (ref.kind === 'array' || ref.kind === 'matrix') {
      return `${ref.kind}<${formatNativeTypeRef(ref.element)}>`;
    }
    return `map<${formatNativeTypeRef(ref.key)}, ${formatNativeTypeRef(ref.value)}>`;
  }
  if (ref === TypeRef.Num) {
    return 'int | float';
  }
  if (ref === TypeRef.Any) {
    return 'any value';
  }
  if (ref === TypeRef.Enum) {
    return 'enum';
  }
  if (ref === TypeRef.Nullable) {
    return 'nullable value';
  }
  if (ref === TypeRef.StringConvertible) {
    return 'scalar | enum | resource';
  }
  return formatType(ref);
}

function formatResult(result: NativeResult): string {
  return result === FirstArgumentResult
    ? 'type of first argument'
    : formatNativeTypeRef(result);
}

function formatParam(param: NativeParam): string {
  const variadic = param.variadic ? '...' : '';
  const optional = param.required ? '' : '?';
  return `${variadic}${param.name}${optional}: ${formatNativeTypeRef(param.type)}`;
}

function formatTypeParams(func: NativeFunc): string {
  if (func.typeParams.length === 0) {
    return '';
  }
  const params = func.typeParams
    .map(param => `${param.name}: ${param.constraint}`)
    .join(', ');
  return `<${params}>`;
}

function formatResultQualifier(
  qualifier: Qualifier | typeof JoinResult,
): string {
  return qualifier === JoinResult ? 'joined from arguments' : qualifier;
}

function paramRules(param: NativeParam): string {
  const rules: string[] = [];
  if (param.availability === 'staged') {
    rules.push('staged; not supported');
  }
  if (param.constLiteral) {
    rules.push('constant literal');
  }
  if (!param.acceptsNa) {
    rules.push('not na');
  }
  if (param.variadic) {
    rules.push('variadic');
  }
  if (param.capture) {
    rules.push('captured expression');
  }
  if (param.mode === 'inout') {
    rules.push('writes receiver');
  }
  return rules.length === 0 ? '—' : rules.join(', ');
}

function overloadSection(
  func: NativeFunc,
  index: number,
  total: number,
): string {
  const params = func.params.map(formatParam).join(', ');
  const signature = `${func.name}${formatTypeParams(func)}(${params}) → ${formatResult(func.result)}`;
  const heading = total === 1 ? '### Signature' : `### Overload ${index + 1}`;
  const rows = func.params
    .map(
      param =>
        `| ${code(param.name)} | ${cell(code(formatNativeTypeRef(param.type)))} | ${code(param.qualifierCap)} | ${param.required ? 'Yes' : 'No'} | ${cell(paramRules(param))} |`,
    )
    .join('\n');
  const table =
    func.params.length === 0
      ? '_No parameters._'
      : [
          '| Parameter | Type | Qualifier cap | Required | Rules |',
          '| --- | --- | --- | --- | --- |',
          rows,
        ].join('\n');
  const display =
    func.inputDefaultDisplay === null
      ? ''
      : `\n\n**Default input display:** ${code(func.inputDefaultDisplay)}`;
  const state = func.stateful ? '\n\n**Call-site state:** Yes' : '';
  return `${heading}

${code(signature)}

${table}

**Result qualifier:** ${code(formatResultQualifier(func.resultQualifier))}

**Native effect class:** ${code(func.effect)}${display}${state}`;
}

export function functionsPage(): string {
  const names = [...CATALOG.funcs.keys()].sort(compare);
  const index = names
    .map(name => `- [${code(name)}](#${anchor('function', name)})`)
    .join('\n');
  const sections = names
    .map(name => {
      const overloads = CATALOG.funcs.get(name) ?? [];
      const body = overloads
        .map((overload, index) =>
          overloadSection(overload, index, overloads.length),
        )
        .join('\n\n');
      return `## ${code(name)} {#${anchor('function', name)}}

${body}`;
    })
    .join('\n\n');
  return `---
title: Functions
description: Compiler-generated reference for Tea native functions.
hide_title: true
---

${GENERATED_WARNING}

# Functions

This page is generated from the checker-owned native function catalog. Overload
order is preserved because it is part of compiler matching behavior.

## Index

${index}

${sections}
`;
}

function category(descriptor: PublicTypeDescriptor): string {
  switch (descriptor.kind) {
    case 'annotation':
      return 'Built-in annotation';
    case 'collection':
      return 'Collection annotation';
    case 'declaration':
      return 'Declared nominal type';
    case 'reference-only':
      return 'Reference-only form';
  }
}

function typeSection(descriptor: PublicTypeDescriptor): string {
  const forms = descriptor.forms.map(code).join(', ');
  const params =
    descriptor.kind !== 'collection'
      ? ''
      : `

**Type parameters:** ${descriptor.typeParams
          .map(param => `${code(param.name)} (${param.constraint})`)
          .join(', ')}`;
  return `## ${code(descriptor.name)} {#${anchor('type', descriptor.name)}}

${descriptor.summary}

**Category:** ${category(descriptor)}

**Source form${descriptor.forms.length === 1 ? '' : 's'}:** ${forms}${params}`;
}

export function typesPage(): string {
  const descriptors = [...PUBLIC_TYPE_CATALOG].sort((left, right) =>
    compare(left.name, right.name),
  );
  const index = descriptors
    .map(
      descriptor =>
        `- [${code(descriptor.name)}](#${anchor('type', descriptor.name)})`,
    )
    .join('\n');
  const sections = descriptors.map(typeSection).join('\n\n');
  return `---
title: Types
description: Compiler-generated reference for Tea source-facing type forms.
hide_title: true
---

${GENERATED_WARNING}

# Types

This page lists the implemented, source-facing type forms.

## Index

${index}

${sections}
`;
}

export function referenceOutputs(root: string): ReadonlyMap<string, string> {
  return new Map([
    [path.join(root, 'docs/reference/types.md'), typesPage()],
    [path.join(root, 'docs/reference/functions.md'), functionsPage()],
  ]);
}

interface GenerateOptions {
  readonly root?: string;
  readonly check?: boolean;
  readonly report?: (message: string) => void;
}

export async function generateReference(
  options: GenerateOptions = {},
): Promise<boolean> {
  const root = options.root ?? path.resolve(import.meta.dir, '../..');
  const check = options.check ?? false;
  const report = options.report ?? (message => console.error(message));
  let stale = false;
  for (const [file, content] of referenceOutputs(root)) {
    const formatted = await format(content, {parser: 'markdown'});
    const source = Bun.file(file);
    const current = (await source.exists()) ? await source.text() : undefined;
    if (current === formatted) {
      continue;
    }
    if (check) {
      stale = true;
      report(`Generated reference is stale: ${path.relative(root, file)}`);
      continue;
    }
    await mkdir(path.dirname(file), {recursive: true});
    await Bun.write(file, formatted);
  }
  if (!stale && check) {
    console.log('Generated Tea reference is current.');
  }
  return !stale;
}

if (import.meta.main) {
  const current = await generateReference({
    check: process.argv.includes('--check'),
  });
  if (!current) {
    process.exitCode = 1;
  }
}
